name: Deploy FastAPI to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/cordobaeats/duo-previa-backend ./backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy duo-previa-backend \
            --image gcr.io/cordobaeats/duo-previa-backend \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated