name: Deploy FastAPI to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/cordoeats-backend ./backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cordoeats-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cordoeats-backend \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars MONGODB_URL=${{ secrets.MONGODB_URL }},JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }},ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }},REFRESH_TOKEN_EXPIRE_DAYS=${{ secrets.REFRESH_TOKEN_EXPIRE_DAYS }},DATABASE_NAME=${{ secrets.DATABASE_NAME }}